[package]
name = "manga_pdf"
version = "0.1.0"
authors = ["Benjamin Cecile <bencecile@gmail.com>"]
edition = "2018"

[dependencies]
lib_stream_pdf = { path = "../lib_stream_pdf" }

rayon = "1.5.3"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
