[package]
name = "manga_pdf"
version = "0.1.0"
authors = ["Benjamin Cecile <bencecile@gmail.com>"]
edition = "2018"

[dependencies]
lib_pdf = { path = "../lib_pdf" }

rayon = "1.2.0"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.40"
